const { DB_NAME, DB_IP, DB_PORT, DB_SECRET, APPLE_ID, APPLE_PASSWORD, APPLE_TEAM_ID, CERTIFICATE_PASSWORD } = process.env
const DB_URL = `${DB_IP}:${DB_PORT}`

export {
  DB_NAME,
  DB_IP,
  DB_PORT,
  DB_SECRET,
  DB_URL,
  APPLE_ID,
  APPLE_PASSWORD,
  APPLE_TEAM_ID,
  CERTIFICATE_PASSWORD
}
