const generate = (type, version, versionFile) => {
  if (type === "HTML") {
    return `
    /*
      This generated by https://github.com/DaimondCat1234567/scratchssenger/blob/main/sodesktop/build.js
      With Node v${process.versions.node}
      V8 ${process.versions.v8}
    */
    <html>
      <head>
        <title>Scratchssenger sosirsOS Build for version ${version}</title>
      </head>
      <body>
        <h1>Enable JavaScript</h1>
      </body>
      <script>
        document.body.innerHTML = \`
          <iframe src="https://scratchssenger.vercel.app/msngrv${versionFile}.html" width="482" height="412" allowtransparency="true" frameborder="0" scrolling="no" allowfullscreen="" style="color-scheme: auto"></iframe>
        \`
      </script>
    </html>
    `
  }
}

export default generate
