const generate = (type, version, versionFile) => {
  if (type === "HTML") {
    return `
    /*
      This generated by https://github.com/DiamondCatGroup/scratchssenger/blob/main/sodesktop/build.js
      With Node v${process.versions.node}
      V8 ${process.versions.v8}
    */
    <html>
      <head>
        <title>Scratchssenger sosirsOS Build for version ${version}</title>
      </head>
      <body>
        <h1>Enable JavaScript</h1>
      </body>
      <script>
        document.body.innerHTML = \`
          <iframe src="https://scratchssenger.vercel.app/msngrv${versionFile}.html" width="482" height="412" allowtransparency="true" frameborder="0" scrolling="no" allowfullscreen="" style="color-scheme: auto"></iframe>
        \`
      </script>
    </html>
    `
  } else if (type === "sosf-gs") {
    return {
      fileType: "GeometryScratch",
      fileVersion: "0.1",
      launchVersion: "0.1",
      gsUrl: `https://scratchssenger.vercel.app/msngrv${versionFile}.html`,
      commentsForScratchssenger: {
        version,
        versions: {
          node: process.version.node,
          v8: process.version.v8,
          generatedBy: "https://github.com/scrajang-studios/scratchssenger/blob/main/sodesktop/build.js"
        },
        title: "scratchssenger"
      }
    }
  } else if (type === "sosf-gp") {
    return {
      fileType: "GeometryPlay",
      fileVersion: "0.1",
      launchVersion: "0.1",
      gpUrl: `https://scratchssenger.vercel.app/msngrv${versionFile}.html`,
      commentsForScratchssenger: {
        version,
        versions: {
          node: process.version.node,
          v8: process.version.v8,
          generatedBy: "https://github.com/scrajang-studios/scratchssenger/blob/main/sodesktop/build.js"
        },
        title: "scratchssenger"
      }
    }
  }
}

export default generate
